dataabc/weibo-crawler

weibo.py

Fixes dataabc/weibo-crawler#108

fix: 修复verified_type的缺省值[issue 108]

---

weibo.py

你好，我在下载图片时，很多图片都不完整裂开了，增加检测图片的完整性后再保存

fix: 图片下载不完整

---

config.json
weibo.py

* `created_at`包含时间，数据分析时还是很有用的
*  经常被微博限制而中途显示已经抓完，所以加了一个`start_page`的配置，可以从断点手动继续抓。

created at contains time now; start_page config.

---

config.json
weibo.py

添加了抓取微博评论功能，新增加两个config参数，download_comment为1代表下载评论，comment_max_download_count每条微博下载评论最大数量限制。目前只储存到sqlite中，如果需要储存到别的地方，可以重构调用get_weibo_comments(self, weibo, max_count, on_downloaded)的方式，注入on_downloaded实现其他储存方式。

feat: comments download

---

README.md

针对评论下载功能更新README.md，包括关于sqlite数据库的说明。

针对评论下载功能更新README.md

---

weibo.py

fix:sqlite写入文件条件判断错误

---

.gitignore
weibo.py

btw, function get_user_info() is frequently denied, sleep time should be optimize.

fix bug #256 , skip when meet invalid id

---

.gitignore
README.md
config.json
const.py
weibo.py

- Fix: Long weibo parsing error due to html structure change. #293 
- Fix: Comments crawler page error.
- Add reposts crawler support when using sqlite.
- Add html parsing for comments crawler.
- Update .gitignore file.
- Add documentation for reposts crawler.

Add some features and fix bugs

---

.dockerignore
Dockerfile
README.md
__main__.py
requirements.txt

- 添加Dockerfile
- 添加__main__.py，使用schedule定时执行脚本
- 更新README.md中docker的使用方法

feat: 支持使用docker容器定时执行

---

weibo.py

让since_date支持时间。issue: #396 
用户在配置文件的第三个字段中可以填入以下3种可用的格式：
- 整数
- 2023-08-29
- 2023-08-29T09:08:23
在爬取完成后会使用第三种格式的时间覆盖该字段

since_date支持时间

---

Dockerfile
requirements.txt
weibo.py

原本的 Dockerfile 无法编译通过，修改了依赖版本号
修正了启用 user_id_as_folder_name 时会崩溃的问题

修正一些无法运行的问题

---

README.md

目前，在完成爬取后，执行程序时间写入文件，修改只存在于container内，并不会保留到host。重启或者重新创建container时又会再从头开始爬取。挂载相应保存user ID的文件后，写入的执行程序时间可得以保留。

Update README.md regarding docker command

---

weibo.py

抱歉，原来的endswith还有检查文件完整性的作用，需要添加回来

Revert file integrity check

---

API.md
README.md
service.py
util/dateutil.py

可以启动一个http服务，提供以下操作：
- 刷新微博
- 查询刷新任务状态
- 获取所有微博
- 获取微博详情

增加了api服务和API接口说明

---

config.json
weibo.py

新增可以控制是否往数据库中写入图片和视频的二进制内容，节省硬盘空间。

新增json选项，是否往数据库中存储二进制内容

---

weibo.py

把1790行至1793行换成
info_list = copy.deepcopy(self.weibo[wrote_count:])

Issues#504修复了当选择sqlite时，转发图片和转发视频无法下载的情况

---

weibo.py

原代码每次请求都调用requests.get()，导致每次都要建立新的TCP连接。创建self.session。用self.session.get替换requests.get()。

优化：为 Weibo 类复用 Session 以减少 TCP 连接开销.

---

README.md
config.json
weibo.py

修改了config.json，weibo.py，README.md，修改详情见每一个提交的description

实现live photo独立下载

---

requirements.txt
test_llm.py
util/llm_analyzer.py
weibo.py

本次 PR 为 weibo-crawler 项目新增了对大语言模型（LLM, Large Language Model）的集成，以增强对微博内容的智能分析能力。该功能的引入将极大提高微博数据在实际分析场景中的价值与效率。
1. **情感分析**：自动识别每条微博的情绪倾向（积极、中性、消极），适用于舆情分析、品牌监控等应用场景。
2. **摘要生成**：针对长微博生成精炼摘要，使用户能够快速把握核心信息。
3. **异常检测**：识别潜在的异常微博，包括谣言、广告、敏感信息等，为内容过滤与监管提供支持。
- 新增配置项至 `config.json`，参数列表如下：
```json
"llm_config": {
"api_base": "your api url",
"api_key": "your api key",
"model": "your model",
"enable_sentiment_analysis": true,
"enable_summary": true,
"enable_anomaly_detection": true,
"max_tokens": 1000,
"temperature": 0.7
}
- 新增模块 `llm_analyzer.py`，封装与大语言模型的调用接口，便于后续拓展与维护。
- 在内容抓取逻辑中加入分析调用，自动处理文本并将分析结果附加至输出数据。
- 支持将分析结果写入 CSV、JSON 等常用格式，保证数据的可视化与可追踪性。
- 新增测试文件 `test_llm.py`：该脚本用于验证大语言模型集成后的主要功能是否正常运行，包括：
- 情感分析：判断输入文本的情绪倾向；
- 摘要生成：提取输入文本的核心信息；
- 异常检测：识别文本中是否包含异常信息；
- 综合分析：模拟一条完整微博数据的整体处理流程。
- …
```

新增功能：集成大语言模型以增强对微博爬取内容分析能力

---

weibo.py

fix #535 
adding refer in header for downloading images and videos without adding proxy.
fix `is_pinned_weibo`, adding `is_pinned_weibo` in `append mode`

adding header for image,video download, fix isTop
